package dev.jimmymcbride.remindmelord.domain.models

import kotlinx.serialization.Serializable

/**
 * Data model used for deserializing verses from the seed JSON file (`verses.json`).
 *
 * This class is used only during initial database population and does not contain an `id` field,
 * since the ID will be auto-generated by Room upon insertion.
 *
 * @property text The content of the verse.
 * @property reference The book, chapter, and verse reference.
 * @property tags A list of descriptive tags associated with the verse.
 */
@Serializable
data class VerseSeed(
    val text: String,
    val reference: String,
    val tags: List<String>
)
