package dev.jimmymcbride.remindmelord.data.entites

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room database entity representing a single Bible verse.
 *
 * This class maps to the `verses` table in the local Room database.
 * Each verse includes the text of the verse, a reference (e.g., "John 3:16"),
 * and a list of associated tags for filtering and categorization.
 *
 * @property id The unique identifier for the verse. Auto-generated by Room.
 * @property text The content of the Bible verse.
 * @property reference The book, chapter, and verse reference (e.g., "Psalm 23:1").
 * @property tags A list of tags describing the verse (e.g., ["peace", "hope"]).
 */
@Entity(tableName = "verses")
data class VerseEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val text: String,
    val reference: String,
    val tags: List<String>
)
